name: builder_dispatcher

on:
  push:
    branches:
      - 'main'
  workflow_call:
    inputs:
      jdk_version:
        description: 'JDK version'
        required: true
        type: string
      CORE:
        description: 'Whether CORE should be run'
        required: true
        type: string
      RTS:
        description: 'Whether RTS should be run'
        required: true
        type: string
      XTS:
        description: 'Whether XTS should be run'
        required: true
        type: string
      JACOCO:
        description: 'Whether JACOCO should be run'
        required: true
        type: string
      pull_request_number:
        description: 'Pull request number'
        required: true
        type: string
      pull_request_repo:
        description: 'Repository to check out'
        required: true
        type: string
        default: 'jbosstm/narayana'
      pull_request_ref:
        description: 'Branch or commit to test'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      jdk_version:
        description: 'JDK version'
        required: true
        type: string
      CORE:
        description: 'Whether CORE should be run'
        required: true
        type: string
      RTS:
        description: 'Whether RTS should be run'
        required: true
        type: string
      XTS:
        description: 'Whether XTS should be run'
        required: true
        type: string
      JACOCO:
        description: 'Whether JACOCO should be run'
        required: true
        type: string
      pull_request_number:
        description: 'Pull request number (optional)'
        required: false
        type: string
      pull_request_repo:
        description: 'Repository to check out'
        required: true
        type: string
        default: 'jbosstm/narayana'
      pull_request_ref:
        description: 'Branch or commit to test (optional)'
        required: false
        type: string

# Only run the latest job
concurrency:
  group: 'builder_dispatcher @ ${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  builder_dispatcher:
    name: Builder and dispatcher with JDK ${{ inputs.jdk_version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    outputs:
      CORE: ${{ inputs.CORE }}
      RTS: ${{ inputs.RTS }}
      XTS: ${{ inputs.XTS }}
      JACOCO: ${{ inputs.JACOCO }}
      jdk_version: ${{ inputs.jdk_version }}
      pr_number: ${{ inputs.pull_request_number }}
      pr_ref: ${{ inputs.pull_request_ref }}
      pr_repo: ${{ inputs.pull_request_repo }}
      narayana_artifact_name: ${{ steps.export-artifacts-names.outputs.narayana_artifact_name }}
      wildfly_artifact_name: ${{ steps.export-artifacts-names.outputs.wildfly_artifact_name }}
      jboss_as_zip_name: ${{ steps.export-jboss-as-zip-name.outputs.jboss_as_zip_name }}

    steps:
      - name: Log run context
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ inputs.pull_request_repo || github.repository }}"
          echo "Branch/Ref: ${{ inputs.pull_request_ref || github.ref }}"
          if [ ! -z "${{ inputs.pull_request_number }}" ]; then
            echo "PR Number: #${{ inputs.pull_request_number }}"
          fi

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: '${{ inputs.pull_request_repo || github.repository }}'
          ref: ${{ inputs.pull_request_ref || github.ref }}

      - name: Set up JDK (${{ inputs.jdk_version }})
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.jdk_version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/jboss/narayana
            !~/.m2/repository/org/wildfly
          key: maven-${{ runner.os }}
          restore-keys: maven-${{ runner.os }}-

      - name: Build Narayana and WildFly
        id: builds
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          NARAYANA_BUILD=1 AS_BUILD=1 ./.github/scripts/narayana.sh
          echo "narayana_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f pom.xml | tr -d '%')" >> $GITHUB_OUTPUT
          echo "wildfly_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f jboss-as/pom.xml | tr -d '%')" >> $GITHUB_OUTPUT

      - name: Export Narayana and WildFly artifact names
        id: export-artifacts-names
        run: |
          echo "narayana_artifact_name=${{ github.run_id }}-narayana-${{ steps.builds.outputs.narayana_version }}-artifacts-jdk${{ inputs.jdk_version }}" >> $GITHUB_OUTPUT
          echo "wildfly_artifact_name=${{ github.run_id }}-wildfly-${{ steps.builds.outputs.wildfly_version }}-artifacts-jdk${{ inputs.jdk_version }}" >> $GITHUB_OUTPUT

      - name: Save Narayana Maven repository
        uses: actions/upload-artifact@v4
        with:
          compression-level: '0'
          retention-days: 1
          name: ${{ steps.export-artifacts-names.outputs.narayana_artifact_name }}
          path: ~/.m2/repository/org/jboss/narayana

      - name: Save WildFly Maven repository
        uses: actions/upload-artifact@v4
        with:
          compression-level: '0'
          retention-days: 1
          name: ${{ steps.export-artifacts-names.outputs.wildfly_artifact_name }}
          path: ~/.m2/repository/org/wildfly

      - name: Export jboss-as zip name
        id: export-jboss-as-zip-name
        run: |
          echo "jboss_as_zip_name=${{ github.run_id }}-jboss-as-zip-jdk${{ inputs.jdk_version }}" >> $GITHUB_OUTPUT

      - name: Save jboss-as
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: ${{ steps.export-jboss-as-zip-name.outputs.jboss_as_zip_name }}
          path: ${{ github.workspace }}/jboss-as/build/target/wildfly-${{ steps.builds.outputs.wildfly_version }}.zip

  CORE:
    needs: builder_dispatcher
    if: ${{ needs.builder_dispatcher.outputs.CORE == 'true' }}
    uses: ./.github/workflows/core.yml
    with:
      jdk_version: ${{ needs.builder_dispatcher.outputs.jdk_version }}
      pull_request_number: ${{ needs.builder_dispatcher.outputs.pr_number }}
      pull_request_ref: ${{ needs.builder_dispatcher.outputs.pr_ref }}
      pull_request_repo: ${{ needs.builder_dispatcher.outputs.pr_repo }}
      narayana_artifact_name: ${{ needs.builder_dispatcher.outputs.narayana_artifact_name }}
      wildfly_artifact_name: ${{ needs.builder_dispatcher.outputs.wildfly_artifact_name }}
      jboss_as_zip_name: ${{ needs.builder_dispatcher.outputs.jboss_as_zip_name }}

  RTS:
    needs: builder_dispatcher
    if: ${{ needs.builder_dispatcher.outputs.RTS == 'true' }}
    uses: ./.github/workflows/rts.yml
    with:
      jdk_version: ${{ needs.builder_dispatcher.outputs.jdk_version }}
      pull_request_number: ${{ needs.builder_dispatcher.outputs.pr_number }}
      pull_request_ref: ${{ needs.builder_dispatcher.outputs.pr_ref }}
      pull_request_repo: ${{ needs.builder_dispatcher.outputs.pr_repo }}
      narayana_artifact_name: ${{ needs.builder_dispatcher.outputs.narayana_artifact_name }}
      wildfly_artifact_name: ${{ needs.builder_dispatcher.outputs.wildfly_artifact_name }}
      jboss_as_zip_name: ${{ needs.builder_dispatcher.outputs.jboss_as_zip_name }}

  XTS:
    needs: builder_dispatcher
    if: ${{ needs.builder_dispatcher.outputs.XTS == 'true' }}
    uses: ./.github/workflows/xts.yml
    with:
      jdk_version: ${{ needs.builder_dispatcher.outputs.jdk_version }}
      pull_request_number: ${{ needs.builder_dispatcher.outputs.pr_number }}
      pull_request_ref: ${{ needs.builder_dispatcher.outputs.pr_ref }}
      pull_request_repo: ${{ needs.builder_dispatcher.outputs.pr_repo }}
      narayana_artifact_name: ${{ needs.builder_dispatcher.outputs.narayana_artifact_name }}
      wildfly_artifact_name: ${{ needs.builder_dispatcher.outputs.wildfly_artifact_name }}
      jboss_as_zip_name: ${{ needs.builder_dispatcher.outputs.jboss_as_zip_name }}

  JACOCO:
    needs: builder_dispatcher
    if: ${{ needs.builder_dispatcher.outputs.JACOCO == 'true' }}
    uses: ./.github/workflows/jacoco.yml
    with:
      jdk_version: ${{ needs.builder_dispatcher.outputs.jdk_version }}
      pull_request_number: ${{ needs.builder_dispatcher.outputs.pr_number }}
      pull_request_ref: ${{ needs.builder_dispatcher.outputs.pr_ref }}
      pull_request_repo: ${{ needs.builder_dispatcher.outputs.pr_repo }}
      narayana_artifact_name: ${{ needs.builder_dispatcher.outputs.narayana_artifact_name }}
      wildfly_artifact_name: ${{ needs.builder_dispatcher.outputs.wildfly_artifact_name }}
      jboss_as_zip_name: ${{ needs.builder_dispatcher.outputs.jboss_as_zip_name }}
